- name: configure frontend dervice
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginix 1.24
    command: dnf module enable nginx:1.24 -y
  - name: install nginix
    package:
      name: nginx
      state: present
  - name: remove html directory
    file:
      path: /usr/share/nginx/html/
      state: absent
  - name: create html directory
    file:
      path: /usr/share/nginx/html/
      state: directory
  